describe ("Home Menu", function() {
    beforeEach(()=>{
        cy.viewport('macbook-15')
    })
    context('Positive Test Suites', function(){
        it ('TCP01-HM-Assert URL', function(){
            cy.visit('https://rahulshettyacademy.com/angularpractice/')
            cy.url().should('contain', 'rahulshettya')
        })
        it ('TCP02--HM-Create Female Student Customer Profile', function(){
            cy.get(':nth-child(1) > .form-control').type('Afiatin Alia Azani')
            cy.get(':nth-child(2) > .form-control').type('afiatinaliaazani@gmail.com')
            cy.get('#exampleInputPassword1').type('@lia412')
            cy.get('#exampleCheck1').click()
            cy.get('#exampleFormControlSelect1').select('Female')
            cy.get('#inlineRadio1').click()
            cy.get(':nth-child(8) > .form-control').invoke('removeAttr','type').type('04/12/1998{enter}')
            cy.get('.btn')
            cy.contains('Success! The Form has been submitted successfully!').should('be.visible')
            })
        it ('TCP03-HM-Create Male Student Customer Profile', function(){
            cy.visit('https://rahulshettyacademy.com/angularpractice/')
            cy.get(':nth-child(1) > .form-control').type('Brian Jacob')
            cy.get(':nth-child(2) > .form-control').type('Brianjacob@gmail.com')
            cy.get('#exampleInputPassword1').type('br1@n123')
            cy.get('#exampleCheck1').click()
            cy.get('#exampleFormControlSelect1').select('Male')
            cy.get('#inlineRadio1').click()
            cy.get(':nth-child(8) > .form-control').invoke('removeAttr','type').type('23/10/1996{enter}')
            cy.get('.btn')
            cy.contains('Success! The Form has been submitted successfully!').should('be.visible')
            })
        it ('TCP04-HM-Create Female Employed Customer Profile', function(){
            cy.visit('https://rahulshettyacademy.com/angularpractice/')
            cy.get(':nth-child(1) > .form-control').type('Georgia Rose')
            cy.get(':nth-child(2) > .form-control').type('G.rose@gmail.com')
            cy.get('#exampleInputPassword1').type('Gr0s3412')
            cy.get('#exampleCheck1').click()
            cy.get('#exampleFormControlSelect1').select('Female')
            cy.get('#inlineRadio2').click()
            cy.get(':nth-child(8) > .form-control').invoke('removeAttr','type').type('08/09/1995{enter}')
            cy.get('.btn')
            cy.contains('Success! The Form has been submitted successfully!').should('be.visible')
            })
        it ('TCP05-HM-Create Male Employed Customer Profile', function(){
            cy.visit('https://rahulshettyacademy.com/angularpractice/')
            cy.get(':nth-child(1) > .form-control').type('Kenneth Mars')
            cy.get(':nth-child(2) > .form-control').type('Kenmars@gmail.com')
            cy.get('#exampleInputPassword1').type('K3NM4r5123')
            cy.get('#exampleCheck1').click()
            cy.get('#exampleFormControlSelect1').select('Male')
            cy.get('#inlineRadio2').click()
            cy.get(':nth-child(8) > .form-control').invoke('removeAttr','type').type('16/10/1994{enter}')
            cy.get('.btn')
            cy.contains('Success! The Form has been submitted successfully!').should('be.visible')
            }) 
        it ('TCP06-HM-Clear and Edit Data', function(){
            cy.get(':nth-child(1) > .form-control').clear()
            cy.get(':nth-child(1) > .form-control').type('Guinevere Alonso')
            cy.get(':nth-child(2) > .form-control').clear()
            cy.get(':nth-child(2) > .form-control').type('Guinalo@gmail.com')
            cy.get('#exampleInputPassword1').clear()
            cy.get('#exampleInputPassword1').type('6u1n@lon50')
            cy.get('#exampleCheck1').click()
            cy.get('#exampleCheck1').click()
            cy.get('#exampleFormControlSelect1').select('Female')
            cy.get('#inlineRadio1').click()
            cy.get(':nth-child(8) > .form-control').invoke('removeAttr','type').clear()
            cy.get(':nth-child(8) > .form-control').invoke('removeAttr','type').type('18/06/1997{enter}')
            cy.get('.btn')
            cy.contains('Success! The Form has been submitted successfully!').should('be.visible')
            })
        })
    context('Negative Test Suites', function(){
        it ('TCN01-HM-Name field Empty', function(){
            cy.get(':nth-child(1) > .form-control').clear()
            cy.get('.btn')
            cy.contains('Name is required').should('be.visible')
        }) 
        it ('TCN02-HM-Email field Empty', function(){
            cy.get(':nth-child(2) > .form-control').clear()
            cy.get('.btn')
            cy.contains('Email is required').should('be.visible')
        })
        it ('TCN03-HM-Password Field Empty', function(){
            cy.visit('https://rahulshettyacademy.com/angularpractice/')
            cy.get(':nth-child(1) > .form-control').type('Kenneth Mars')
            cy.get(':nth-child(2) > .form-control').type('Kenmars@gmail.com')
            cy.get('#exampleCheck1').click()
            cy.get('#exampleFormControlSelect1').select('Male')
            cy.get('#inlineRadio2').click()
            cy.get(':nth-child(8) > .form-control').invoke('removeAttr','type').type('16/10/1994{enter}')
            cy.get('.btn')
            cy.contains('Success! The Form has been submitted successfully!').should('be.visible') // Advice: Error message "Password is Required" should be visible and submit button should hover and unclickable
        })
        it ('TCN04-HM-Submit without fill all field', function(){
            cy.visit('https://rahulshettyacademy.com/angularpractice/')
            cy.get('.btn').click()
            cy.contains('Success! The Form has been submitted successfully!.').should('be.visible') //Advice: Error Message on Name Field and Email field should be visible and submit button should hover and unclickable
        })
        it ('TCN05-HM-Assert Disable Radio Button', function(){
            cy.visit('https://rahulshettyacademy.com/angularpractice/')
            cy.get(':nth-child(1) > .form-control').type('Kenneth Mars')
            cy.get(':nth-child(2) > .form-control').type('Kenmars@gmail.com')
            cy.get('#exampleInputPassword1').type('K3NM4r5123')
            cy.get('#exampleCheck1').click()
            cy.get('#exampleFormControlSelect1').select('Male')
            cy.get('#inlineRadio3').should('be.disabled')
        })
    })
})